environments:
  dev:
    kubeContext: data-core-eks-dev
  prod:
    kubeContext: data-core-eks-prod
releases:
  - name: data-portal-frontend-{{ .Environment.Name }}
    namespace: default
    chart: ./k8ss/data-portal-frontend
    version: 0.1.0
    values:
      - k8s/data-portal-frontend/values-{{ .Environment.Name }}.yaml
      - k8s/data-portal-frontend/values.yaml.gotmpl
