# Deployment - deprecated example (extensions/v1beta1) +
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deprecated-deployment
  labels:
    app: deprecated-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deprecated-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
---
# Ingress - deprecated example (networking.k8s.io/v1beta1)
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: deprecated-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-service
              servicePort: 80
---
# DaemonSet - deprecated example (extensions/v1beta1)
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deprecated-daemonset
  labels:
    app: deprecated-daemon
spec:
  selector:
    matchLabels:
      app: deprecated-daemon
  template:
    metadata:
      labels:
        app: deprecated-daemon
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "3600"]